export const REQUEST_PARKS = 'REQUEST_PARKS';
export const GET_PARKS_FAILURE = 'GET_PARKS_FAILURE';
export const GET_PARKS_SUCCESS = 'GET_PARKS_SUCCESS';
export const DELETE_PARK = 'DELETE_PARK';
export const ADD_PARK = 'ADD_PARK';
export const PARK_LIST = 'PARK_LIST';
export const SEE_FORM = 'SEE_FORM';
export const SELECTED_PARK = 'SELECTED_PARK';
export const LANDING_PAGE = 'LANDING_PAGE';
export const UNSELECT_PARK = 'UNSELECT_PARK';
// Might not be needed
export const SEE_PARK = 'SEE_PARK';